sudo: required

services:
  - docker

before_install:
  - docker build -t 2598nitz/docker-react -f Dcokerfile.dev .

script:
  - docker run -e CI=true 2598nitz/docker-react npm run test -- --coverage 